name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: "20 */4 * * *"

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
